### DISCUSSION TITLE
Honoring rustfmt.

### DISCUSSION THREAD

**Discussion by madelaney** [mrcjkb/rustaceanvim#75] [Announcements]
All,

When using `vim.lsp.buf.format`, the fact that I have a `.rustfmt.toml` file seems to be ignored as the formatting does not follow the expected configuration.

```rust
vim.api.nvim_create_autocmd('BufWritePre', {
  group = au_group,
  buffer = bufnr,
  callback = function()
    vim.lsp.buf.format({
      timeoiut_ms = 2000,
      async = false,
    })
  end,
})
```

Do I need to do anything special to for the lsp formatter to respect my config?

**Comment by mrcjkb** [comment]
:thinking: it doesn't seem to be picking up .rustfmt.toml for me, either.
This is probably a rust-analyzer issue. I will see if I have some time to look into it tomorrow.

**Reply by madelaney** [reply]
Thanks for looking into this. Please let me know if I can help.

**Reply by mrcjkb** [reply]
I just realised I was playing with unstable rustfmt options in an attempt to reproduce this.
With stable options (e.g., `max_width`), it works fine on my end.

To enable unstable options, you need use a nightly build of rustfmt, and set the option:

```lua
vim.g.rustaceanvim = {
  server = {
    settings = {
      ['rust-analyzer'] = {
        rustfmt = {
          extraArgs = { '--unstable-features' },
        },
      },
    },
  },
}
```

You can see which options are stable in [the rustfmt docs](https://rust-lang.github.io/rustfmt/) (make sure to select the correct version).

Note that rust-analyzer [does not respect ignore configs](https://github.com/rust-lang/rust-analyzer/issues/10826), because it provides the file contents to rustfmt via stdin.

**Reply by madelaney** [reply]
Thanks @mrcjkb! Based on your comment above, I found this solution:
```lua
  {
    'mrcjkb/rustaceanvim',
    version = '^3', -- Recommended
    ft = { 'rust' },
    init = function()
      vim.g.rustaceanvim = {
        server = {
          settings = {
            ['rust-analyzer'] = {
              rustfmt = {
                extraArgs = { '+nightly', '--unstable-features' },
              },
            },
          },
        },
      }
    end,
  },
```

**Comment by 9mm** [comment]
If anyone came across this it was quite a bit of convoluted path. I actually chose not to put all this in rust-analyzer, but make it project specific via toml files.

```
rustup install nightly
rustup component add rust-analyzer
```

nvim config:

```lua
["rust-analyzer"] = {
  cargo = {
    features = "all",
  },
},
```

**rust-toolchain.toml**

```toml
[toolchain]
channel = "nightly"
```

**rustfmt.toml**

```toml
# https://rust-lang.github.io/rustfmt/?version=v1.6.0

# stable
newline_style = "Unix"

# unstable
# imports_granularity = "Crate"
group_imports = "One"
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
unstable_features = true
version = "Two"
wrap_comments = true
```
