### ISSUE TITLE
openWorkspaceCargo command

### ISSUE THREAD

**Issue by Madoshakalaka** [mrcjkb/rustaceanvim#629]
### Feature description

`OpenCargo` has been very useful, but I find myself often need to navigate to the workspace Cargo.toml to tweak workspace deps there, especially when you have some crate cargo.toml like this..
```toml
[dependencies]
axum = "0.7.9"
serde = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = "0.3.19"
```
...

What's better, I suggest an `openAllCargoSplit` command that opens both the crate's Cargo.toml and the workspace's side by side
